language: java
sudo: true
# dist: trusty

os:
  - linux

jdk:
  - openjdk8

install:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B

script:
  - mvn -Dtest=ObjectOrientedTest test -pl EvosuiteTest -e -Dorg.slf4j.simpleLogger.defaultLogLevel=warn
